version: 0.0
os: linux
files:
  - source: /
    destination: /tomcat/applications/test8180
    overwrite: yes 
permissions:
  - object: /
    owner: tomcat
    group: tomcat
    type:
      - file
hooks:
 ApplicationStop:
    - location: /stop_server.sh
      timeout: 300
runas: tomcat
BeforeInstall:
    - location: /clean_server.sh
      timeout: 300
      runas: tomcat
ApplicationStart:
    - location: /start.sh
      timeout: 300
      runas: tomcat

