version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codedeploy-test
    overwrite: yes 
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    type:
      - file
hooks:
 ApplicationStop:
    - location: Scripts/stop_server.sh
      timeout: 300
runas: tomcat
BeforeInstall:
    - location: Scripts/clean_server.sh
      timeout: 300
      runas: tomcat
ApplicationStart:
    - location: Scripts/start.sh
      timeout: 300
      runas: tomcat

