spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
      
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names:
    - thymeleaf/*


server:
  port: 80
  
  ssl:
     enabled: true
     key-store: certificate.p12
     key-store-type: "PKCS12"
     key-store-password: vlutest
     key-alias: vlutest.tk
  http2:
    enabled: true

    


   
    
           
        
        