spring:
  profiles:
    group:
      local : local,common
      
---
spring:
  config:
    activate:
      on-profile:
      - local
       
        
server:
    port:
        8080
    ssl:
      enabled: true
      key-store-type: "PKC12"
      key-alias: vlutest.tk
   
---
spring:                        
  config:
    activate:
      on-profile:
      - dev 
server:
    port:
        8080

---
spring:
  config:
    activate:
      on-profile:
      - prd


server:
    port:
        8080

        
---
spring:
  config:
    activate:
      on-profile: 
      - common
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names:
    - thymeleaf/*
 

---
spring:
 config:
    activate:
      on-profile: 
      - localdb







    


   
    
           
        
        