spring:
  profiles:
    group:
      local : local,common, localdb
      
---
spring:
  config:
    activate:
      on-profile:
      - local
       
        
server:
    port:
        8082
        


---
spring:
  config:
    activate:
      on-profile:
      - dev 
server:
    port:
        8081

---
spring:
  config:
    activate:
      on-profile:
      - prd


server:
    port:
        8082

        
---
spring:
  config:
    activate:
      on-profile: 
      - common
      
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/   
    suffix: .html  
    cache: false 
    view-names: post/*
    
  jpa:
    database: oracle
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    '[org.hibernate]': info
    


---
spring:
 config:
    activate:
      on-profile: 
      - localdb
 datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1522/xe
    username: test_user
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver




    


   
    
           
        
        